### ISSUE TITLE
put method issu

### ISSUE THREAD

**Issue by p3im4n** [Ansh-Rathod/Photoarc-app-backend-nodejs#1]
hi Mr @Ansh-Rathod 
I found out none of the put methods are fired in the backend...

I'm working on it

could you give me some clue???

**Comment by Ansh-Rathod** [comment]
were you testing in postman? or any other platform?

**Comment by p3im4n** [comment]
postman

**Comment by p3im4n** [comment]
I correct my last quote
only like and unlike put-method are not fired in creat-post.js

**Comment by Ansh-Rathod** [comment]
okk let me check

**Comment by Ansh-Rathod** [comment]
check your console what did it show when you try to call like route?

**Comment by p3im4n** [comment]
it show nothing

**Comment by p3im4n** [comment]
I must tell somthing
I test it in my own backend not yours
this is my domain: disn.ir

**Comment by Ansh-Rathod** [comment]
change put to post and try again or try to print something on console or check route is it correct or not

**Comment by Ansh-Rathod** [comment]
```
{
          "user_id": uid,
          "liker_id": likerid,
          "time_at": DateTime.now().toString(),
          "post_id": postid,
        }
```

required parameters when you call put method for like post

**Comment by p3im4n** [comment]
it's so wired....
I changed the route name to what else 'like'
and it works fine!!!!!
it turns out like the 'like' word is reserved !!!
it doesn't make any sense!! doesn't it????

**Comment by Ansh-Rathod** [comment]
okay now its working fine? try unlike too
